version: '3.3'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=user
      - N8N_BASIC_AUTH_PASSWORD=password
    volumes:
      - ./.n8n:/home/node/.n8n
      - ./dist/nodes/:/home/node/.n8n/custom
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 1G
  